# Generated by Django 5.0.1 on 2024-01-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_number_or_trucks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='number_or_trucks',
            new_name='number_of_trucks',
        ),
    ]
