# Generated by Django 5.0.1 on 2024-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_card_number_or_trucks_card_number_of_trucks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='address_line',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='contact_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='email_address',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='fuel_cards_register',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='mailing_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='mc_dot_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='primary_contact_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='zip_code',
            field=models.CharField(max_length=255),
        ),
    ]
