# Generated by Django 5.0.1 on 2024-01-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_address_line_alter_card_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number_of_trucks',
            field=models.IntegerField(),
        ),
    ]
