# Generated by Django 5.0.1 on 2024-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_number_of_trucks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.FileField(max_length=500, upload_to='files/'),
        ),
    ]
