# Generated by Django 5.0.1 on 2024-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_card_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
