# Generated by Django 5.0.1 on 2024-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number_or_trucks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
